---
- name: Prepare Servers to Deploy OpenStack
  hosts: controller-1
  remote_user: ubuntu
  become: true
  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install needed packages for Kolla-Ansible
      apt:
        name:
          - git
          - python3-dev
          - python3-pip
          - libffi-dev
          - gcc
          - libssl-dev
          - python3-docker
          - python3-setuptools
        state: present

    - name: Create kolla directory
      shell: mkdir -p /etc/kolla;

    - name: Install kolla-ansible dependencies
      pip:
        name: kolla-ansible
        state: present

    - name: Upgrade ansible via pip3
      pip:
        name: ansible
        state: latest

    - name: Copy kolla config files
      shell: cp /usr/local/share/kolla-ansible/etc_examples/kolla/* /etc/kolla; 

    - name: kolla-ansible install-deps
      shell: kolla-ansible install-deps

    - name: kolla-genpwd
      shell: kolla-genpwd
